#!/usr/bin/env python3
r"""Run the Direction 01 sweep / confirmation runs (MASTER_PLAN §3.2, §8).

**RUN LATER — GPU (per-run runtime in §8).** Iterates the arm/seed configs and
trains each via ``singnet.train.run``. Fully resumable: a run whose registry row
already shows ``steps_done >= steps`` is skipped, and an interrupted run resumes
from its last checkpoint (so a Colab disconnect costs minutes, §12).

    # the 15-run sweep (5 arms x 3 seeds), REDUCED budget
    python scripts/run_sweep.py --stage reduced

    # the exploratory lambda pair (clearly labelled), REDUCED budget
    python scripts/run_sweep.py --stage reduced --exploratory

    # confirmation: generate + run the 3 FULL configs (top-2 by mean val SI-SDR
    # + l1mag) after the sweep analysis is frozen
    python scripts/run_sweep.py --stage full

    # apply the §3.2 budget-halving rule (REDUCED 8k / FULL 20k) for ALL arms
    python scripts/run_sweep.py --stage reduced --halve
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from singnet.train import get_run, make_run_id, read_registry, run  # noqa: E402
from singnet.utils.config import hash_config, resolve_config  # noqa: E402

CONFIG_DIR = Path("01-loss-function-study/configs")
REGISTRY = "01-loss-function-study/results/registry.csv"
ARMS = ["l1mag", "msemag", "logl1mag", "sisdr", "l1mrstft"]
SEEDS = [0, 1, 2]
REDUCED_STEPS, FULL_STEPS = 16000, 40000


def _already_done(config_path: Path) -> bool:
    """True if the registry shows this config completed to its step budget."""
    cfg = resolve_config(config_path)
    run_id = make_run_id(cfg["arm"], cfg["seed"], cfg.get("budget_name", "custom"), hash_config(cfg))
    row = get_run(REGISTRY, run_id)
    return bool(row) and int(row.get("steps_done", 0)) >= int(cfg["steps"])


def _run_config(config_path: Path) -> None:
    if _already_done(config_path):
        print(f"skip (already complete): {config_path.name}")
        return
    print(f"running {config_path.name} (RUN LATER: GPU)")
    result = run(config_path, registry_path=REGISTRY)
    print(f"  -> {result}")


def reduced(exploratory: bool) -> list[Path]:
    configs = [CONFIG_DIR / f"{arm}_seed{seed}_reduced.yaml" for arm in ARMS for seed in SEEDS]
    if exploratory:
        configs += [CONFIG_DIR / "l1mrstft_lam025_seed0_reduced.yaml",
                    CONFIG_DIR / "l1mrstft_lam100_seed0_reduced.yaml"]
    return configs


def generate_full_configs(steps: int) -> list[Path]:
    """Pick top-2 arms by mean val SI-SDR (+ l1mag) and write their FULL configs.

    Reads the sweep registry; requires the 15 reduced runs to have completed. The
    generated files are ``{arm}_seed0_full.yaml`` (MASTER_PLAN §10, "generated").
    """
    frame = read_registry(REGISTRY)
    if frame.empty:
        raise SystemExit("registry empty — run the reduced sweep first (RUN LATER)")
    reduced_rows = frame[frame["budget"] == REDUCED_STEPS]
    means = reduced_rows.groupby("arm")["best_val_sisdr"].mean().sort_values(ascending=False)
    top2 = list(means.head(2).index)
    chosen = list(dict.fromkeys([*top2, "l1mag"]))[:3]
    print(f"confirmation arms (top-2 by mean val SI-SDR + l1mag): {chosen}")

    paths: list[Path] = []
    for arm in chosen:
        body = (
            f"# CONFIRMATION run (MASTER_PLAN §3.2): {arm}, seed 0, FULL budget.\n"
            f"# Generated by run_sweep.py from the frozen reduced-sweep ranking.\n"
            f"base: base.yaml\narm: {arm}\nseed: 0\nbudget_name: full\nsteps: {steps}\n"
        )
        path = CONFIG_DIR / f"{arm}_seed0_full.yaml"
        path.write_text(body, encoding="utf-8")
        paths.append(path)
    return paths


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--stage", required=True, choices=["reduced", "full"])
    parser.add_argument("--exploratory", action="store_true", help="also run the 2 lambda configs (reduced only)")
    parser.add_argument("--halve", action="store_true", help="apply the §3.2 budget-halving rule")
    args = parser.parse_args(argv)

    if args.stage == "reduced":
        configs = reduced(args.exploratory)
    else:
        full_steps = FULL_STEPS // 2 if args.halve else FULL_STEPS
        configs = generate_full_configs(full_steps)

    print(f"stage={args.stage}: {len(configs)} configs")
    for config_path in configs:
        if not config_path.exists():
            raise SystemExit(f"missing config {config_path} (did config generation run?)")
        _run_config(config_path)


if __name__ == "__main__":
    main()
